<?php
/**
 * Warehouse shipment item new line to manage warehouse selection
 *
 * @copyright   Copyright (c) 2016 MagentoCrew
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @var MagentoCrew_Warehouse_Block_Adminhtml_Sales_Order_Shipment_Create_Items_Warehouses $this
 */

$warehouses = $this->getAvailableWarehouses();
?>
<tr>
    <td>
        <?php if (!count($warehouses)): ?>
            <span class="error"><strong><?php echo $this->__('Error: '); ?></strong><?php echo $this->__('This product is no longer available in any warehouses!'); ?></span>
        <?php endif; ?>

    </td>
    <td colspan="2" class="nobr a-left" style="padding: 5px 10px 20px 10px;">
        <?php if (count($warehouses)): ?>
            <strong class="nobr" style="padding-right: 10px ;"><?php echo $this->__('Ship from: ') ?></strong>

            <select name="shipment[warehouses][598]" class="select required-entry">
                <?php if (count($warehouses) > 1): ?>
                    <option value=""><?php echo $this->__('-- Please select warehouse --'); ?></option>
                <?php endif; ?>

                <?php foreach ($warehouses as $warehouse): ?>
                    <option value="<?php echo $warehouse->getId(); ?>"><?php echo $warehouse->getName(); ?></option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
    </td>
</tr>