<?php
/**
 * Warehouse catalog product view info
 *
 * @copyright   Copyright (c) 2016 MagentoCrew
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * 
 * @var MagentoCrew_Warehouse_Block_Catalog_Product_View_Warehouse $this 
 */
?>
<div class="product-warehouse">
    <?php echo $this->__('Available in next warehouses: '). implode(", ", $this->getWarehouses());?>
</div>
